# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c0b446fd459bce47c1aecaa461d8ac19"
name = "BadgeHQ"
handle = "badgehq"
application_url = "https://badge-hq.vercel.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_script_tags,read_script_tags,read_themes,read_orders,write_orders"

[auth]
redirect_urls = [
  "https://badge-hq.vercel.app/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [webhooks.privacy_compliance]
  customer_data_request_url = "/webhooks/customers/data_request"
  customer_deletion_url = "/webhooks/customers/redact"
  shop_deletion_url = "/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[app_proxy]
url = "https://badge-hq.vercel.app"
subpath = "badgehq"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
