-- Standalone P&L app config (single-row, id='default').
--
-- The tool at /pnl-app authenticates to Shopify with a CUSTOM-APP Admin API
-- token (generated by the brand in their own admin), which — unlike the
-- distributed BadgeHQ app — has Protected Customer Data access automatically,
-- so it can read orders without PCD approval. Credentials are server-side only.
--
-- Idempotent, matching every migration since 0008.
CREATE TABLE IF NOT EXISTS "PnlApp" (
  "id"                 TEXT NOT NULL DEFAULT 'default',
  "passwordHash"       TEXT NOT NULL DEFAULT '',
  "shopDomain"         TEXT NOT NULL DEFAULT '',
  "adminToken"         TEXT NOT NULL DEFAULT '',
  "shiprocketEmail"    TEXT NOT NULL DEFAULT '',
  "shiprocketPassword" TEXT NOT NULL DEFAULT '',
  "delhiveryApiKey"    TEXT NOT NULL DEFAULT '',
  "metaAccessToken"    TEXT NOT NULL DEFAULT '',
  "metaAdAccountId"    TEXT NOT NULL DEFAULT '',
  "lastSyncAt"         TIMESTAMP(3),
  "lastSyncStatus"     TEXT NOT NULL DEFAULT '',
  "createdAt"          TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt"          TIMESTAMP(3) NOT NULL,
  CONSTRAINT "PnlApp_pkey" PRIMARY KEY ("id")
);
